FROM caddy:2-builder AS builder

RUN xcaddy build v2.7.3 \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2

FROM caddy:2-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "docker-proxy"]
